### ISSUE TITLE
BUG mc backup of helm chart needs zu quote password

### ISSUE THREAD

**Issue by Heiko-san** [clastix/kamaji-etcd#43]
Hi,

we created an additional datastore of type etcd using your helm chart clastix/kamaji-etcd. 
We successfully set up it with an s3 backup. However in our values.yaml we had to define our password like this (not the real pwd):

``` yaml
  s3:
    #...
    bucket: kamaji/kamaji-etcd-2/
    accessKey: kamaji
    secretKey: "'xY%foo$ba)R'"
```

This is necessary so that the single quotes get added to the mc command, otherwise shell would try to interpret the password.
Maybe in the containers command, the password should be quoted by default.

We use kamaji v0.3.3 together with cluster-api v1.5.0 with infrastructure-vsphere v1.7.0 and your kamaji plugin control-plane-kamaji v0.3.0.
