### ISSUE TITLE
service account missing

### ISSUE THREAD

**Issue by Heiko-san** [clastix/kamaji-etcd#46]
Hi @prometherion ,

I think there is a new bug here:

I'm using the following values.yaml (which is basically a modified version of the original one):

``` yaml
#cat kamaji-etcd_values.yaml| grep -Ev '^\s*(#|$)'
replicas: 5
serviceAccount:
  create: true
  name: ""
image:
  repository: quay.io/coreos/etcd
  tag: ""
  pullPolicy: IfNotPresent
peerApiPort: 2380
clientPort: 2379
metricsPort: 2381
livenessProbe: {}
extraArgs: []
autoCompactionMode: periodic
autoCompactionRetention: 5m
snapshotCount: "10000"
quotaBackendBytes: "8589934592" # 8Gi
persistenVolumeClaim:
  size: 2Gi
  storageClassName: "block-small-sc"
  accessModes:
  - ReadWriteOnce
  customAnnotations: {}
defragmentation:
  schedule: "*/15 * * * *" # https://crontab.guru/
backup:
  enabled: true
  all: false
  schedule: "*/15 * * * *" # https://crontab.guru/
  snapshotNamePrefix: kpoc-tenant1
  snapshotDateFormat: $(date +%Y%m%d-%H%M)
  s3:
    url: https:/s3.our.domain
    bucket: kamaji/kpoc-tenant1-etcd/
    retention: "--expiry-days 3"
    accessKey:
      valueFrom:
        secretKeyRef:
          key: access_key
          name: minio-key
    secretKey:
      valueFrom:
        secretKeyRef:
          key: secret_key
          name: minio-key
    image:
      repository: minio/mc
      tag: "RELEASE.2022-11-07T23-47-39Z"
      pullPolicy: IfNotPresent
podLabels:
  application: kpoc-tenant1-etcd
podAnnotations: {}
securityContext:
  allowPrivilegeEscalation: false
priorityClassName: system-cluster-critical
resources:
  limits: {}
  requests: {}
nodeSelector:
  kubernetes.io/os: linux
tolerations: []
affinity: {}
topologySpreadConstraints: []
datastore:
  enabled: true
serviceMonitor:
  enabled: false
  namespace: ''
  labels: {}
  annotations: {}
  matchLabels: {}
  targetLabels: []
  serviceAccount:
    name: etcd
    namespace: etcd-system
  endpoint:
    interval: "15s"
    scrapeTimeout: ""
    metricRelabelings: []
    relabelings: []
alerts:
  enabled: false
  namespace: ''
  labels: {}
  annotations: {}
  rules: []
```

If I apply this with your fork (from back, when you implemented #43 (branch "issues/43", commit "a521b27d830f4bf16908f03cab146039ab4a1401" is what I have still checked out), then everything works fine.

``` sh
helm install kpoc-tenant1-etcd ~/tmp/kamaji/kamaji-etcd-prometherion/charts/kamaji-etcd -n kpoc-tenant1 -f kamaji-etcd_values.yaml
```

``` sh
kg job
#NAME                                COMPLETIONS   DURATION   AGE
#kpoc-tenant1-etcd-backup-28253640   1/1           6m22s      21m
#kpoc-tenant1-etcd-backup-28253655   1/1           9s         6m22s
#kpoc-tenant1-etcd-defrag-28253640   1/1           80s        21m
#kpoc-tenant1-etcd-defrag-28253655   1/1           81s        6m22s
#kpoc-tenant1-etcd-etcd-setup-1      1/1           94s        33m
kg sa
#NAME                SECRETS   AGE
#default             0         33m
#kpoc-tenant1-etcd   0         33m
```

However, if I apply the very same config with the latest upstream branch, then it doesn't work because the relevant serviceaccount is not created:

``` sh 
helm install kpoc-tenant2-etcd clastix/kamaji-etcd -n kpoc-tenant2 -f kamaji-etcd_values.yaml
```

``` sh
kg job
#NAME                                COMPLETIONS   DURATION   AGE
#kpoc-tenant2-etcd-backup-28253655   0/1           8m27s      8m27s
#kpoc-tenant2-etcd-defrag-28253655   0/1           8m27s      8m27s
kg sa
#NAME      SECRETS   AGE
#default   0         16m
k describe job kpoc-tenant2-etcd-backup-28253655
#...
#  Warning  FailedCreate  5m6s (x6 over 9m56s)  job-controller  Error creating: pods "kpoc-tenant2-etcd-backup-28253655-" is forbidden: error looking up service account kpoc-tenant2/kpoc-tenant2-etcd: serviceaccount "kpoc-tenant2-etcd" not found
```

And actually ... while ensuring I can reproduce the issue, I found, that the sa is actually created and then seems to be deleted after install has finished:

``` sh
kg sa
#NAME                SECRETS   AGE
#default             0         113s
#kpoc-tenant2-etcd   0         75s
kg sa
#NAME      SECRETS   AGE
#default   0         2m6s
```
