### ISSUE TITLE
Set the name of datastore

### ISSUE THREAD

**Issue by bsctl** [clastix/kamaji-etcd#65]
Currenlty the name of the datastore is created as the name of the release:

```yaml
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
```

It would be useful to leave the user to choose a different name:

```yaml
datastore:
  # -- Create a datastore custom resource for Kamaji
  enabled: true
  # -- Name of Kamaji datastore, set to Release Name when null or not provided
  # name: default
```
