### ISSUE TITLE
Use different cluster job selector for metrics scraping

### ISSUE THREAD

**Issue by bsctl** [clastix/kamaji-etcd#74]
When enabling Prometheus **ServiceMonitor** on multiple `kamaji-etcd` instances, all the ServiceMonitors use the same job selector based on the `app.kubernetes.io/name=kamaji-etcd` label. This leads Prometheus to consider all the `kamaji-etcd` instances as part of a single `etcd` cluster when collecting and displaying metrics.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: roma-capitale
    meta.helm.sh/release-namespace: roma-capitale
  labels:
    app.kubernetes.io/instance: roma-capitale
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kamaji-etcd
    app.kubernetes.io/version: 3.5.6
    helm.sh/chart: kamaji-etcd-0.7.0
  name: roma-capitale-monitor
  namespace: monitoring-system
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - roma-capitale
  selector:
    matchLabels:
      app.kubernetes.io/instance: roma-capitale
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kamaji-etcd                             <<<<< this selector
      app.kubernetes.io/version: 3.5.6
      helm.sh/chart: kamaji-etcd-0.7.0
```

A simple solution is to force Prometheus to use a different label as for example:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: roma-capitale
    meta.helm.sh/release-namespace: roma-capitale
  labels:
    app.kubernetes.io/instance: roma-capitale
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kamaji-etcd
    app.kubernetes.io/version: 3.5.6
    helm.sh/chart: kamaji-etcd-0.7.0
  name: roma-capitale-monitor
  namespace: monitoring-system
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  jobLabel: app.kubernetes.io/instance    <<<<< this selector
  namespaceSelector:
    matchNames:
    - roma-capitale
  selector:
    matchLabels:
      app.kubernetes.io/instance: roma-capitale
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kamaji-etcd
      app.kubernetes.io/version: 3.5.6
      helm.sh/chart: kamaji-etcd-0.7.0
```
