### ISSUE TITLE
Default Service Account for metrics

### ISSUE THREAD

**Issue by bsctl** [clastix/kamaji-etcd#77]
Currently, the default Service Account for metrics refers a not existing namespace:

```yaml
serviceMonitor:
  # -- Enable ServiceMonitor for Prometheus
  enabled: false
  serviceAccount:
    # -- ServiceAccount for Metrics RBAC
    name: etcd
    # -- ServiceAccount Namespace for Metrics RBAC
    namespace: etcd-system
```

By enabling the Service Monitor, default values point to a not existing service account and namespace.
By default it should be set to service account in the release namespace.
