### ISSUE TITLE
maybe the storageClass value name is wrong

### ISSUE THREAD

**Issue by lixd** [clastix/kamaji-etcd#9]
in template used `storageClassName`:
```yaml
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.persistenVolumeClaim.storageClassName }}
        accessModes:
        {{- range .Values.persistenVolumeClaim.accessModes }}
        - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistenVolumeClaim.size }}
```
but in values.yaml named `storageClass`
```yaml
persistenVolumeClaim:
  # -- The size of persistent storage for etcd data 
  size: 10Gi
  # -- A specific storage class
  storageClass: ""
  # -- The Access Mode to storage
  accessModes:
  - ReadWriteOnce
```
try to specify storageClass by `helm install xxx --set persistenVolumeClaim.storageClass=xxx` not work,and i edit values.yaml to storageClassName it works.

or is there a specical usage? i am a new fish for helm.
